import json
from datetime import datetime

from automl_agent.core.llm import get_llm
from automl_agent.core.state import AgentState, FinalReport


def _rule_based_report(state: AgentState) -> str:
    """Fallback plain markdown report when LLM is unavailable."""
    info = state.dataset_info
    metrics = state.evaluator_insight.metrics if state.evaluator_insight else {}
    arch = state.ml_config.architecture if state.ml_config else "N/A"
    hp = state.ml_config.hyperparams if state.ml_config else {}
    critic = state.critic_decision
    training = state.training_result

    lines = [
        f"# Experiment Report: {info.name}",
        f"*Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "---",
        "",
        "## Dataset Summary",
        f"- **File:** {info.name}",
        f"- **Task:** {info.task_type.capitalize()}",
        f"- **Rows:** {info.n_samples}",
        f"- **Features:** {info.n_features}",
        f"- **Target column:** {info.target_column}",
        f"- **Class balance:** {info.class_balance}" if info.class_balance else "",
        f"- **Imbalanced:** {'Yes' if info.is_imbalanced else 'No'}",
        f"- **Missing ratio:** {info.missing_ratio:.1%}",
        "",
        "## Planner Strategy",
    ]

    if state.planner_decision:
        lines += [
            f"- **Optuna trials:** {state.planner_decision.optuna_trials}",
            f"- **Max retries:** {state.planner_decision.max_retries}",
            f"- **Strategy:** {state.planner_decision.strategy_notes}",
            "- **Risk flags:**",
        ] + [f"  - {r}" for r in state.planner_decision.risk_flags]
    else:
        lines.append("- No planner decision recorded.")

    lines += [
        "",
        "## Data Analysis",
    ]

    if state.analyst_insight:
        lines += [
            f"{state.analyst_insight.interpretation}",
            "",
            "**Risks identified:**",
        ] + [f"- {r}" for r in state.analyst_insight.risks] + [
            "",
            "**Recommendations:**",
        ] + [f"- {r}" for r in state.analyst_insight.recommendations]
    else:
        lines.append("No analyst insight recorded.")

    lines += [
        "",
        "## Model Selection",
        f"- **Architecture:** {arch}",
    ]

    if state.selector_decision:
        lines += [
            f"- **Reasoning:** {state.selector_decision.reasoning}",
            f"- **Alternatives considered:** "
            f"{', '.join(state.selector_decision.alternatives_considered) or 'None'}",
        ]

    lines += [
        "",
        "## Training",
        f"- **Final hyperparameters:** `{json.dumps(hp, indent=2)}`",
    ]

    if training:
        lines += [
            f"- **Best epoch:** {training.best_epoch + 1}",
            f"- **Best validation loss:** {training.best_val_loss:.4f}",
            f"- **Training time:** {training.training_time_s:.1f}s",
            f"- **Retry count:** {state.retry_count}",
        ]

    lines += [
        "",
        "## Results",
    ]

    for k, v in metrics.items():
        lines.append(f"- **{k}:** {v}")

    if state.evaluator_insight:
        lines += [
            "",
            f"**Interpretation:** {state.evaluator_insight.interpretation}",
        ]
        if state.evaluator_insight.strengths:
            lines += ["", "**Strengths:**"] + [
                f"- {s}" for s in state.evaluator_insight.strengths
            ]
        if state.evaluator_insight.critical_failures:
            lines += ["", "**Critical failures:**"] + [
                f"- {f}" for f in state.evaluator_insight.critical_failures
            ]

    lines += [
        "",
        "## Critic Decision",
    ]

    if critic:
        status = "Approved" if critic.approved else "Not approved"
        lines += [
            f"- **Status:** {status}",
            f"- **Score:** {critic.score}/10",
            f"- **Reasoning:** {critic.reasoning}",
        ]
        if critic.retry_strategy:
            lines.append(f"- **Retry strategy used:** {critic.retry_strategy}")
    else:
        lines.append("No critic decision recorded.")

    lines += [
        "",
        "## Recommendations",
        "_Run with a Groq API key for LLM-generated recommendations._",
        "",
        "---",
        "*Report generated by Agentic AutoML Pipeline*",
    ]

    return "\n".join(line for line in lines if line is not None)


def reporter_agent(state: AgentState) -> AgentState:
    state.current_step = "reporting"
    state.add_log("Reporter: generating final experiment report.")

    llm = get_llm()

    if llm:
        # build a rich context dict for the LLM
        context = {
            "dataset": {
                "name":          state.dataset_info.name,
                "rows":          state.dataset_info.n_samples,
                "features":      state.dataset_info.n_features,
                "task":          state.dataset_info.task_type,
                "imbalanced":    state.dataset_info.is_imbalanced,
                "missing_ratio": state.dataset_info.missing_ratio,
                "class_balance": state.dataset_info.class_balance,
            },
            "planner": state.planner_decision.model_dump()
                       if state.planner_decision else {},
            "analyst": state.analyst_insight.model_dump()
                       if state.analyst_insight else {},
            "selector": state.selector_decision.model_dump()
                        if state.selector_decision else {},
            "hyperparameters": state.ml_config.hyperparams
                               if state.ml_config else {},
            "architecture": state.ml_config.architecture
                            if state.ml_config else "N/A",
            "training": {
                "best_epoch":      state.training_result.best_epoch + 1
                                   if state.training_result else None,
                "best_val_loss":   state.training_result.best_val_loss
                                   if state.training_result else None,
                "training_time_s": state.training_result.training_time_s
                                   if state.training_result else None,
                "retry_count":     state.retry_count,
            },
            "evaluation": state.evaluator_insight.model_dump()
                          if state.evaluator_insight else {},
            "critic": state.critic_decision.model_dump()
                      if state.critic_decision else {},
        }

        prompt = f"""
You are writing a professional ML experiment report for a data scientist.
Be specific — reference actual numbers from the experiment data below.
Do not be generic. Every section should reflect the actual experiment.

Experiment data:
{json.dumps(context, indent=2)}

Write a complete markdown report with exactly these sections:

# Experiment Report: {state.dataset_info.name}

## Dataset Summary
Describe the dataset, task type, size, class distribution, 
and key challenges specific to these numbers.

## Planner Strategy
Explain what strategy was chosen before training and why, 
referencing the risk flags and past experiment history.

## Data Analysis
Summarize the analyst's findings. Explain the risks identified 
and what they mean for model performance on this specific dataset.

## Model Selection
Explain why {state.ml_config.architecture if state.ml_config else 'the chosen model'} 
was selected. Mention what alternatives were considered and why they were ruled out.

## Training Process
Describe the training: Optuna tuning, final hyperparameters chosen, 
best epoch, validation loss, and whether retries were triggered.

## Results
Interpret the metrics — not just numbers but what they mean 
for this specific problem. For medical datasets highlight recall. 
For regression highlight R2 and RMSE in context.

## Critical Analysis
What worked well. What failed or underperformed. 
Known limitations of the current approach.

## Recommendations
Give 4-5 specific, actionable next steps to improve this model.
Reference the actual metrics and failures — not generic advice.

Be technical and precise. The reader is an ML engineer.
"""
        try:
            report_md = llm.invoke(prompt).content.strip()

            # clean up if model wraps in markdown fences
            if report_md.startswith("```"):
                report_md = report_md.split("```")[1]
                if report_md.startswith("markdown"):
                    report_md = report_md[8:]
            report_md = report_md.strip()

            state.final_report = FinalReport(full_markdown=report_md)
            state.add_log("Reporter: LLM report generated successfully.")

        except Exception as exc:
            state.add_log(f"Reporter: LLM failed ({exc}), using rule-based report.")
            state.final_report = FinalReport(
                full_markdown=_rule_based_report(state)
            )
    else:
        state.add_log("Reporter: no API key, using rule-based report.")
        state.final_report = FinalReport(
            full_markdown=_rule_based_report(state)
        )

    return state